main = "./dist/index.js"

[build]
command = "npm run build"

[vars]

[durable_objects]
bindings = [
    { name = "TEMPLATES", class_name = "Templates" }
]

kv_namespaces = [
  { binding = "SUPABASE_TOKENS", id = "" }
]

migrations = []
