[build]
command = "npm run build"

main = "./dist/index.js"

[vars]

[durable_objects]
bindings = [
    { name = "TEMPLATES", class_name = "Templates" }
]

[kv_namespaces]
bindings = [
  { name = "SUPABASE_TOKENS", id = "" }
]
